name: Build APK
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04 # Daha stabil versiya
    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build with Buildozer
        uses: ArtemSBulgakov/buildozer-action@v1.6.1 # Versiyanı dəqiqləşdirdik
        with:
          command: buildozer android debug
          buildozer_version: master
          
